docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Introduction: v1/intro.md
site_name: mezzio-authorization-acl
site_description: 'ACL authorization middleware for Mezzio and PSR-7 applications'
repo_url: 'https://github.com/mezzio/mezzio-authorization-acl'
