docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Introduction: v1/intro.md
site_name: zend-expressive-authorization-acl
site_description: 'ACL permission adapter for zend-expressive-authorization.'
repo_url: 'https://github.com/zendframework/zend-expressive-authorization-acl'
